// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SupportTicketAPI.Data;

#nullable disable

namespace SupportTicketAPI.Data.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260616062331_UpdateSeedUsers")]
    partial class UpdateSeedUsers
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("SupportTicketAPI.Models.KnowledgeBaseArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Body")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("KnowledgeBaseArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Body = "Click 'Forgot Password' on the login page, type in your email address, and click the link in the reset email. The link is valid for 24 hours.",
                            CreatedAt = new DateTime(2026, 6, 7, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            Tags = "password,reset",
                            Title = "Resetting your password"
                        },
                        new
                        {
                            Id = 2,
                            Body = "Our standard response times are: Critical - 2 hours, High - 8 hours, Medium - 24 hours, Low - 72 hours.",
                            CreatedAt = new DateTime(2026, 6, 9, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 3,
                            Tags = "sla,priority",
                            Title = "SLA response times"
                        });
                });

            modelBuilder.Entity("SupportTicketAPI.Models.Ticket", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("AssignedToUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("CreatedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<bool>("IsSlaBreached")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Priority")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("SlaDeadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AssignedToUserId");

                    b.HasIndex("CreatedByUserId");

                    b.ToTable("Tickets");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Tried logging in multiple times but it just says 401 unauthorized. I'm sure the password is correct.",
                            IsSlaBreached = false,
                            Priority = "High",
                            SlaDeadline = new DateTime(2026, 6, 12, 8, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Open",
                            Title = "Login fails with 401 error"
                        },
                        new
                        {
                            Id = 2,
                            AssignedToUserId = 3,
                            CreatedAt = new DateTime(2026, 6, 11, 21, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Checked my card statement and I was billed twice this month. Only one order confirmation received.",
                            IsSlaBreached = true,
                            Priority = "Critical",
                            SlaDeadline = new DateTime(2026, 6, 11, 23, 0, 0, 0, DateTimeKind.Utc),
                            Status = "InProgress",
                            Title = "Charged twice for subscription"
                        },
                        new
                        {
                            Id = 3,
                            AssignedToUserId = 3,
                            CreatedAt = new DateTime(2026, 6, 10, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Requested a password reset but the email never arrived in my inbox or spam.",
                            IsSlaBreached = false,
                            Priority = "Low",
                            SlaDeadline = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Resolved",
                            Title = "Forgot password reset link not arriving"
                        },
                        new
                        {
                            Id = 4,
                            AssignedToUserId = 3,
                            CreatedAt = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Is there any way to turn on dark mode? The white screen is a bit too bright for night use.",
                            IsSlaBreached = false,
                            Priority = "Medium",
                            SlaDeadline = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "PendingCustomer",
                            Title = "Dark mode support?"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            CreatedByUserId = 1,
                            Description = "Clicking the export button does nothing. Tried on Chrome and Safari, no file downloads.",
                            IsSlaBreached = false,
                            Priority = "Medium",
                            SlaDeadline = new DateTime(2026, 6, 13, 0, 0, 0, 0, DateTimeKind.Utc),
                            Status = "Open",
                            Title = "CSV export button not working"
                        });
                });

            modelBuilder.Entity("SupportTicketAPI.Models.TicketComment", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TicketId");

                    b.HasIndex("UserId");

                    b.ToTable("TicketComments");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.TicketHistory", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("ChangedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ChangedByUserId")
                        .HasColumnType("int");

                    b.Property<string>("NewStatus")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<string>("OldStatus")
                        .HasColumnType("longtext");

                    b.Property<int>("TicketId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChangedByUserId");

                    b.HasIndex("TicketId");

                    b.ToTable("TicketHistories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ChangedAt = new DateTime(2026, 6, 11, 22, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 3,
                            NewStatus = "InProgress",
                            Note = "Assigned to Bob. Checking payment gateway logs.",
                            OldStatus = "Open",
                            TicketId = 2
                        },
                        new
                        {
                            Id = 2,
                            ChangedAt = new DateTime(2026, 6, 10, 1, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 3,
                            NewStatus = "InProgress",
                            Note = "Investigating email logs.",
                            OldStatus = "Open",
                            TicketId = 3
                        },
                        new
                        {
                            Id = 3,
                            ChangedAt = new DateTime(2026, 6, 11, 0, 0, 0, 0, DateTimeKind.Utc),
                            ChangedByUserId = 3,
                            NewStatus = "Resolved",
                            Note = "Manually triggered reset link.",
                            OldStatus = "InProgress",
                            TicketId = 3
                        });
                });

            modelBuilder.Entity("SupportTicketAPI.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("TenantId")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "alice@demo.com",
                            Name = "Alice",
                            PasswordHash = "$2a$11$EjA4/XEdoTEun6S.mVWcCesE7GlBuztGkkPZiLiRWmWKoesKFETtK",
                            Role = "Customer",
                            TenantId = "default"
                        },
                        new
                        {
                            Id = 2,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "banni@gmail.com",
                            Name = "Banni",
                            PasswordHash = "$2a$11$EjA4/XEdoTEun6S.mVWcCesE7GlBuztGkkPZiLiRWmWKoesKFETtK",
                            Role = "Customer",
                            TenantId = "default"
                        },
                        new
                        {
                            Id = 3,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "bob@demo.com",
                            Name = "Bob",
                            PasswordHash = "$2a$11$EjA4/XEdoTEun6S.mVWcCesE7GlBuztGkkPZiLiRWmWKoesKFETtK",
                            Role = "Agent",
                            TenantId = "default"
                        },
                        new
                        {
                            Id = 4,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "manav@gmail.com",
                            Name = "Manav",
                            PasswordHash = "$2a$11$EjA4/XEdoTEun6S.mVWcCesE7GlBuztGkkPZiLiRWmWKoesKFETtK",
                            Role = "Customer",
                            TenantId = "default"
                        },
                        new
                        {
                            Id = 5,
                            CreatedAt = new DateTime(2026, 6, 12, 0, 0, 0, 0, DateTimeKind.Utc),
                            Email = "carol@demo.com",
                            Name = "Carol",
                            PasswordHash = "$2a$11$EjA4/XEdoTEun6S.mVWcCesE7GlBuztGkkPZiLiRWmWKoesKFETtK",
                            Role = "Supervisor",
                            TenantId = "default"
                        });
                });

            modelBuilder.Entity("SupportTicketAPI.Models.KnowledgeBaseArticle", b =>
                {
                    b.HasOne("SupportTicketAPI.Models.User", "CreatedBy")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.Ticket", b =>
                {
                    b.HasOne("SupportTicketAPI.Models.User", "AssignedTo")
                        .WithMany("AssignedTickets")
                        .HasForeignKey("AssignedToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("SupportTicketAPI.Models.User", "CreatedBy")
                        .WithMany("CreatedTickets")
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedTo");

                    b.Navigation("CreatedBy");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.TicketComment", b =>
                {
                    b.HasOne("SupportTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("Comments")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SupportTicketAPI.Models.User", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("User");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.TicketHistory", b =>
                {
                    b.HasOne("SupportTicketAPI.Models.User", "ChangedBy")
                        .WithMany()
                        .HasForeignKey("ChangedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SupportTicketAPI.Models.Ticket", "Ticket")
                        .WithMany("History")
                        .HasForeignKey("TicketId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ChangedBy");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.Ticket", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("History");
                });

            modelBuilder.Entity("SupportTicketAPI.Models.User", b =>
                {
                    b.Navigation("AssignedTickets");

                    b.Navigation("Comments");

                    b.Navigation("CreatedTickets");
                });
#pragma warning restore 612, 618
        }
    }
}
